# Configuration Spring Boot
server:
  port: ${PORT}
spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: bank-app

  # Database - les variables viennent du .env
  datasource:
      url: ${LOCAL_DB_URL}
      username: ${LOCAL_DB_USERNAME}
      password: ${LOCAL_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  # Thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  # Security (basic)
  security:
    user:
      name: admin
      password: admin123
